name: flutter_gg
description: "An example project which is written using Flutter gg."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  animate_do: ^3.3.4
  flutter:
    sdk: flutter
  flutter_gg: ^0.0.2
  # flutter_gg:
  #   path: packages/flutter_gg

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
